name = "claude-code-primer"
compatibility_date = "2024-01-01"

[site]
bucket = "./"
exclude = ["node_modules/**", ".git/**", "test-results/**", "*.log", "*.tar.gz", "research/**"]

[[routes]]
pattern = "claude-code-primer.franzai.com/*"
zone_name = "franzai.com"